version: '3'

services:
  db:
    image: 'postgres:latest'
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - sucatech:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  sucatech:
